name: Sync Jobs API Requests

on:
  schedule:
    - cron: "54 09 * * *"  # Run at 1:20 UTC
    - cron: "0 12 * * *"
    - cron: "0 18 * * *"
    - cron: "0 0 */2 * *"
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  sync-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Timestamp and Signature
        id: generate-security-headers
        run: |
          timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          signature=$(echo -n "$timestamp" | openssl dgst -sha256 -hmac "${{ secrets.API_KEY }}" | awk '{print $2}')
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "signature=$signature" >> $GITHUB_OUTPUT
      
      - name: Determine and Trigger Jobs by UTC Hour
        run: |
          hour=$(date -u +"%H")
          minute=$(date -u +"%M")
          day=$(date -u +"%d")
          
          echo "Current UTC time: $hour:$minute"
          echo "Current UTC day: $day"
          
          timestamp="${{ steps.generate-security-headers.outputs.timestamp }}"
          signature="${{ steps.generate-security-headers.outputs.signature }}"
          
          if [[ "$hour" == "09"  && "$minute" == "54" || "$hour" == "18" ]]; then
            echo "Triggering JSearch..."
            curl -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=jsearch" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature"
          fi
          
          if [[ "$hour" == "12" ]]; then
            echo "Triggering Indeed..."
            curl -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=indeed" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature"
            
            echo "Triggering Apify LinkedIn..."
            curl -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=apify_linkedin" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature"
          fi
          
          if (( day % 2 == 0 )) && [[ "$hour" == "00" ]]; then
            echo "Triggering LinkedIn (every 2 days at 00:00 UTC)..."
            curl -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=linkedin" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature"
          fi