name: Sync Jobs API Requests
on:
  schedule:
    - cron: "36 10 * * *"  # Run at 10:04 UTC
    - cron: "0 12 * * *"   # Run at 12:00 UTC
    - cron: "0 18 * * *"   # Run at 18:00 UTC
    - cron: "0 0 */2 * *"  # Run at 00:00 UTC every 2 days
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  sync-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Timestamp and Signature
        id: generate-security-headers
        run: |
          timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          signature=$(echo -n "$timestamp" | openssl dgst -sha256 -hmac "${{ secrets.API_KEY }}" | awk '{print $2}')
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "signature=$signature" >> $GITHUB_OUTPUT
      
      - name: Determine and Trigger Jobs by UTC Time
        run: |
          hour=$(date -u +"%H")
          minute=$(date -u +"%M")
          day=$(date -u +"%d")
          
          echo "Current UTC time: $hour:$minute"
          echo "Current UTC day: $day"
          
          timestamp="${{ steps.generate-security-headers.outputs.timestamp }}"
          signature="${{ steps.generate-security-headers.outputs.signature }}"
          
          # Debugging info
          echo "Workflow triggered at hour=$hour minute=$minute day=$day"
          echo "Using timestamp: $timestamp"
          echo "API URL: ${{ secrets.API_URL }}"
          
          # Run JSearch at 10:04 UTC and 18:00 UTC
          if [[ "$hour" == "10" && "$minute" == "36" ]] || [[ "$hour" == "18" && "$minute" == "00" ]]; then
            echo "Triggering JSearch..."
            response=$(curl -v -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=jsearch" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature")
            echo "JSearch API Response: $response"
          fi
          
          # Run Indeed and Apify LinkedIn at 12:00 UTC
          if [[ "$hour" == "12" && "$minute" == "00" ]]; then
            echo "Triggering Indeed..."
            response=$(curl -v -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=indeed" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature")
            echo "Indeed API Response: $response"
            
            echo "Triggering Apify LinkedIn..."
            response=$(curl -v -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=apify_linkedin" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature")
            echo "Apify LinkedIn API Response: $response"
          fi
          
          # Run LinkedIn every 2 days at 00:00 UTC
          if [[ "$hour" == "00" && "$minute" == "00" ]] && (( day % 2 == 0 )); then
            echo "Triggering LinkedIn (every 2 days at 00:00 UTC)..."
            response=$(curl -v -X POST "https://${{ secrets.API_URL }}/api/jobs/sync?source=linkedin" \
              -H "Origin: ${{ secrets.ORIGIN }}" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.API_KEY }}" \
              -H "X-Timestamp: $timestamp" \
              -H "X-Signature: $signature")
            echo "LinkedIn API Response: $response"
          fi